# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d340a861168b874d6b01b9f5bcfb5c614b6821e923d24146827cb5af091efd8c8ba0f60b956dff02384c9a86fc81353500a9076300e4dc9e36fda8553bd91450

test:
  secret_key_base: b8860b8f178ba2cff062d1220a728a5caf8cb5503163aa1bce28297792c4556a3669e581da4cfc2b515721546baa5d01b51df67ab6ce2e5f79934a01f1f7d358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
